// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    otel_logs: {
        name: "otel_logs";
        parameters: {
          /** STRING - use sql.string() */
          table_name: SQLStringMarker;
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
          /** STRING - use sql.string() */
          severity: SQLStringMarker;
          /** STRING - use sql.string() */
          search: SQLStringMarker;
        };
        result: unknown;
      };
    otel_logs_severity_counts: {
        name: "otel_logs_severity_counts";
        parameters: {
          /** STRING - use sql.string() */
          table_name: SQLStringMarker;
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: unknown;
      };
    otel_metrics: {
        name: "otel_metrics";
        parameters: {
          /** STRING - use sql.string() */
          table_name: SQLStringMarker;
          /** STRING - use sql.string() */
          metric_name: SQLStringMarker;
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: unknown;
      };
    otel_metrics_names: {
        name: "otel_metrics_names";
        parameters: {
          /** STRING - use sql.string() */
          table_name: SQLStringMarker;
        };
        result: unknown;
      };
    otel_spans: {
        name: "otel_spans";
        parameters: {
          /** STRING - use sql.string() */
          table_name: SQLStringMarker;
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
          /** STRING - use sql.string() */
          service: SQLStringMarker;
          /** STRING - use sql.string() */
          roots_only: SQLStringMarker;
        };
        result: unknown;
      };
    otel_trace: {
        name: "otel_trace";
        parameters: {
          /** STRING - use sql.string() */
          table_name: SQLStringMarker;
          /** STRING - use sql.string() */
          trace_id: SQLStringMarker;
        };
        result: unknown;
      };
    otel_validate_table: {
        name: "otel_validate_table";
        parameters: {
          /** STRING - use sql.string() */
          table_name: SQLStringMarker;
        };
        result: unknown;
      };
  }
}
